export const LOGIN_REQUEST = "auth/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "auth/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "auth/LOGIN_FAILURE";

export const FETCH_CURRENT_USER_REQUEST = "auth/FETCH_CURRENT_USER_REQUEST";
export const FETCH_CURRENT_USER_SUCCESS = "auth/FETCH_CURRENT_USER_SUCCESS";
export const FETCH_CURRENT_USER_FAILURE = "auth/FETCH_CURRENT_USER_FAILURE";

export const FETCH_AUTH_ALL_USERS_REQUEST = "auth/FETCH_AUTH_ALL_USERS_REQUEST";
export const FETCH_AUTH_ALL_USERS_SUCCESS = "auth/FETCH_AUTH_ALL_USERS_SUCCESS";
export const FETCH_AUTH_ALL_USERS_FAILURE = "auth/FETCH_AUTH_ALL_USERS_FAILURE";


export const SET_SIMULATED_ROLE = "auth/SET_SIMULATED_ROLE";
export const LOGOUT = "auth/LOGOUT";
