export const FETCH_SETTINGS_CONFIG_REQUEST = "FETCH_SETTINGS_CONFIG_REQUEST";
export const FETCH_SETTINGS_CONFIG_SUCCESS = "FETCH_SETTINGS_CONFIG_SUCCESS";
export const FETCH_SETTINGS_CONFIG_FAILURE = "FETCH_SETTINGS_CONFIG_FAILURE";

export const UPDATE_SCHOOL_CONFIG_REQUEST = "UPDATE_SCHOOL_CONFIG_REQUEST";
export const UPDATE_SCHOOL_CONFIG_SUCCESS = "UPDATE_SCHOOL_CONFIG_SUCCESS";
export const UPDATE_SCHOOL_CONFIG_FAILURE = "UPDATE_SCHOOL_CONFIG_FAILURE";

export const CREATE_USER_CONFIG_REQUEST = "CREATE_USER_CONFIG_REQUEST";
export const CREATE_USER_CONFIG_SUCCESS = "CREATE_USER_CONFIG_SUCCESS";
export const CREATE_USER_CONFIG_FAILURE = "CREATE_USER_CONFIG_FAILURE";

export const UPDATE_USER_CONFIG_REQUEST = "UPDATE_USER_CONFIG_REQUEST";
export const UPDATE_USER_CONFIG_SUCCESS = "UPDATE_USER_CONFIG_SUCCESS";
export const UPDATE_USER_CONFIG_FAILURE = "UPDATE_USER_CONFIG_FAILURE";

export const DELETE_USER_CONFIG_REQUEST = "DELETE_USER_CONFIG_REQUEST";
export const DELETE_USER_CONFIG_SUCCESS = "DELETE_USER_CONFIG_SUCCESS";
export const DELETE_USER_CONFIG_FAILURE = "DELETE_USER_CONFIG_FAILURE";

export const CLEAR_SETTINGS_CONFIG_MESSAGES = "CLEAR_SETTINGS_CONFIG_MESSAGES";
