export const FETCH_SCHOOLS_REQUEST = "school/FETCH_SCHOOLS_REQUEST";
export const FETCH_SCHOOLS_SUCCESS = "school/FETCH_SCHOOLS_SUCCESS";
export const FETCH_SCHOOLS_FAILURE = "school/FETCH_SCHOOLS_FAILURE";
export const SET_ACTIVE_SCHOOL = "school/SET_ACTIVE_SCHOOL";
