export const FETCH_NOTICES_REQUEST = "notices/FETCH_NOTICES_REQUEST";
export const FETCH_NOTICES_SUCCESS = "notices/FETCH_NOTICES_SUCCESS";
export const FETCH_NOTICES_FAILURE = "notices/FETCH_NOTICES_FAILURE";

export const CREATE_NOTICE_REQUEST = "notices/CREATE_NOTICE_REQUEST";
export const CREATE_NOTICE_SUCCESS = "notices/CREATE_NOTICE_SUCCESS";
export const CREATE_NOTICE_FAILURE = "notices/CREATE_NOTICE_FAILURE";

export const UPDATE_NOTICE_REQUEST = "notices/UPDATE_NOTICE_REQUEST";
export const UPDATE_NOTICE_SUCCESS = "notices/UPDATE_NOTICE_SUCCESS";
export const UPDATE_NOTICE_FAILURE = "notices/UPDATE_NOTICE_FAILURE";

export const DELETE_NOTICE_REQUEST = "notices/DELETE_NOTICE_REQUEST";
export const DELETE_NOTICE_SUCCESS = "notices/DELETE_NOTICE_SUCCESS";
export const DELETE_NOTICE_FAILURE = "notices/DELETE_NOTICE_FAILURE";
