export const FETCH_CLASS_TEACHER_CONFIG_REQUEST = "FETCH_CLASS_TEACHER_CONFIG_REQUEST";
export const FETCH_CLASS_TEACHER_CONFIG_SUCCESS = "FETCH_CLASS_TEACHER_CONFIG_SUCCESS";
export const FETCH_CLASS_TEACHER_CONFIG_FAILURE = "FETCH_CLASS_TEACHER_CONFIG_FAILURE";

export const ASSIGN_CLASS_TEACHER_REQUEST = "ASSIGN_CLASS_TEACHER_REQUEST";
export const ASSIGN_CLASS_TEACHER_SUCCESS = "ASSIGN_CLASS_TEACHER_SUCCESS";
export const ASSIGN_CLASS_TEACHER_FAILURE = "ASSIGN_CLASS_TEACHER_FAILURE";

export const CLEAR_CLASS_TEACHER_CONFIG_MESSAGES = "CLEAR_CLASS_TEACHER_CONFIG_MESSAGES";
