export const FETCH_STUDENTS_REQUEST = "students/FETCH_STUDENTS_REQUEST";
export const FETCH_STUDENTS_SUCCESS = "students/FETCH_STUDENTS_SUCCESS";
export const FETCH_STUDENTS_FAILURE = "students/FETCH_STUDENTS_FAILURE";

export const CREATE_STUDENT_REQUEST = "students/CREATE_STUDENT_REQUEST";
export const CREATE_STUDENT_SUCCESS = "students/CREATE_STUDENT_SUCCESS";
export const CREATE_STUDENT_FAILURE = "students/CREATE_STUDENT_FAILURE";

export const UPDATE_STUDENT_REQUEST = "students/UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "students/UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_FAILURE = "students/UPDATE_STUDENT_FAILURE";

export const DELETE_STUDENT_REQUEST = "students/DELETE_STUDENT_REQUEST";
export const DELETE_STUDENT_SUCCESS = "students/DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_FAILURE = "students/DELETE_STUDENT_FAILURE";
