export const FETCH_CLASS_SUBJECT_CONFIG_REQUEST = "FETCH_CLASS_SUBJECT_CONFIG_REQUEST";
export const FETCH_CLASS_SUBJECT_CONFIG_SUCCESS = "FETCH_CLASS_SUBJECT_CONFIG_SUCCESS";
export const FETCH_CLASS_SUBJECT_CONFIG_FAILURE = "FETCH_CLASS_SUBJECT_CONFIG_FAILURE";

export const SYNC_CLASS_SUBJECTS_REQUEST = "SYNC_CLASS_SUBJECTS_REQUEST";
export const SYNC_CLASS_SUBJECTS_SUCCESS = "SYNC_CLASS_SUBJECTS_SUCCESS";
export const SYNC_CLASS_SUBJECTS_FAILURE = "SYNC_CLASS_SUBJECTS_FAILURE";

export const BATCH_CREATE_CLASSES_REQUEST = "BATCH_CREATE_CLASSES_REQUEST";
export const BATCH_CREATE_CLASSES_SUCCESS = "BATCH_CREATE_CLASSES_SUCCESS";
export const BATCH_CREATE_CLASSES_FAILURE = "BATCH_CREATE_CLASSES_FAILURE";

export const DELETE_CLASS_GROUP_REQUEST = "DELETE_CLASS_GROUP_REQUEST";
export const DELETE_CLASS_GROUP_SUCCESS = "DELETE_CLASS_GROUP_SUCCESS";
export const DELETE_CLASS_GROUP_FAILURE = "DELETE_CLASS_GROUP_FAILURE";

export const CLEAR_CLASS_SUBJECT_CONFIG_MESSAGES = "CLEAR_CLASS_SUBJECT_CONFIG_MESSAGES";
