export const FETCH_SUBJECT_TEACHER_CONFIG_REQUEST = "subjectTeacherConfig/FETCH_SUBJECT_TEACHER_CONFIG_REQUEST";
export const FETCH_SUBJECT_TEACHER_CONFIG_SUCCESS = "subjectTeacherConfig/FETCH_SUBJECT_TEACHER_CONFIG_SUCCESS";
export const FETCH_SUBJECT_TEACHER_CONFIG_FAILURE = "subjectTeacherConfig/FETCH_SUBJECT_TEACHER_CONFIG_FAILURE";

export const FETCH_CONFIG_TEACHERS_REQUEST = "subjectTeacherConfig/FETCH_CONFIG_TEACHERS_REQUEST";
export const FETCH_CONFIG_TEACHERS_SUCCESS = "subjectTeacherConfig/FETCH_CONFIG_TEACHERS_SUCCESS";
export const FETCH_CONFIG_TEACHERS_FAILURE = "subjectTeacherConfig/FETCH_CONFIG_TEACHERS_FAILURE";

export const FETCH_CONFIG_CLASSES_REQUEST = "subjectTeacherConfig/FETCH_CONFIG_CLASSES_REQUEST";
export const FETCH_CONFIG_CLASSES_SUCCESS = "subjectTeacherConfig/FETCH_CONFIG_CLASSES_SUCCESS";
export const FETCH_CONFIG_CLASSES_FAILURE = "subjectTeacherConfig/FETCH_CONFIG_CLASSES_FAILURE";

export const ASSIGN_SUBJECT_TEACHER_REQUEST = "subjectTeacherConfig/ASSIGN_SUBJECT_TEACHER_REQUEST";
export const ASSIGN_SUBJECT_TEACHER_SUCCESS = "subjectTeacherConfig/ASSIGN_SUBJECT_TEACHER_SUCCESS";
export const ASSIGN_SUBJECT_TEACHER_FAILURE = "subjectTeacherConfig/ASSIGN_SUBJECT_TEACHER_FAILURE";

export const CLEAR_CONFIG_MESSAGES = "subjectTeacherConfig/CLEAR_CONFIG_MESSAGES";
