export const FETCH_FEES_REQUEST = "fees/FETCH_FEES_REQUEST";
export const FETCH_FEES_SUCCESS = "fees/FETCH_FEES_SUCCESS";
export const FETCH_FEES_FAILURE = "fees/FETCH_FEES_FAILURE";

export const CREATE_FEE_REQUEST = "fees/CREATE_FEE_REQUEST";
export const CREATE_FEE_SUCCESS = "fees/CREATE_FEE_SUCCESS";
export const CREATE_FEE_FAILURE = "fees/CREATE_FEE_FAILURE";

export const UPDATE_FEE_REQUEST = "fees/UPDATE_FEE_REQUEST";
export const UPDATE_FEE_SUCCESS = "fees/UPDATE_FEE_SUCCESS";
export const UPDATE_FEE_FAILURE = "fees/UPDATE_FEE_FAILURE";

export const DELETE_FEE_REQUEST = "fees/DELETE_FEE_REQUEST";
export const DELETE_FEE_SUCCESS = "fees/DELETE_FEE_SUCCESS";
export const DELETE_FEE_FAILURE = "fees/DELETE_FEE_FAILURE";
