export const FETCH_TEACHERS_REQUEST = "teachers/FETCH_TEACHERS_REQUEST";
export const FETCH_TEACHERS_SUCCESS = "teachers/FETCH_TEACHERS_SUCCESS";
export const FETCH_TEACHERS_FAILURE = "teachers/FETCH_TEACHERS_FAILURE";
