export const FETCH_TEACHERS_REQUEST = "teachers/FETCH_TEACHERS_REQUEST";
export const FETCH_TEACHERS_SUCCESS = "teachers/FETCH_TEACHERS_SUCCESS";
export const FETCH_TEACHERS_FAILURE = "teachers/FETCH_TEACHERS_FAILURE";

export const CREATE_TEACHER_REQUEST = "teachers/CREATE_TEACHER_REQUEST";
export const CREATE_TEACHER_SUCCESS = "teachers/CREATE_TEACHER_SUCCESS";
export const CREATE_TEACHER_FAILURE = "teachers/CREATE_TEACHER_FAILURE";

export const UPDATE_TEACHER_REQUEST = "teachers/UPDATE_TEACHER_REQUEST";
export const UPDATE_TEACHER_SUCCESS = "teachers/UPDATE_TEACHER_SUCCESS";
export const UPDATE_TEACHER_FAILURE = "teachers/UPDATE_TEACHER_FAILURE";

export const DELETE_TEACHER_REQUEST = "teachers/DELETE_TEACHER_REQUEST";
export const DELETE_TEACHER_SUCCESS = "teachers/DELETE_TEACHER_SUCCESS";
export const DELETE_TEACHER_FAILURE = "teachers/DELETE_TEACHER_FAILURE";
