export const FETCH_TIMETABLES_REQUEST = "timetables/FETCH_TIMETABLES_REQUEST";
export const FETCH_TIMETABLES_SUCCESS = "timetables/FETCH_TIMETABLES_SUCCESS";
export const FETCH_TIMETABLES_FAILURE = "timetables/FETCH_TIMETABLES_FAILURE";

export const CREATE_TIMETABLE_REQUEST = "timetables/CREATE_TIMETABLE_REQUEST";
export const CREATE_TIMETABLE_SUCCESS = "timetables/CREATE_TIMETABLE_SUCCESS";
export const CREATE_TIMETABLE_FAILURE = "timetables/CREATE_TIMETABLE_FAILURE";

export const UPDATE_TIMETABLE_REQUEST = "timetables/UPDATE_TIMETABLE_REQUEST";
export const UPDATE_TIMETABLE_SUCCESS = "timetables/UPDATE_TIMETABLE_SUCCESS";
export const UPDATE_TIMETABLE_FAILURE = "timetables/UPDATE_TIMETABLE_FAILURE";

export const DELETE_TIMETABLE_REQUEST = "timetables/DELETE_TIMETABLE_REQUEST";
export const DELETE_TIMETABLE_SUCCESS = "timetables/DELETE_TIMETABLE_SUCCESS";
export const DELETE_TIMETABLE_FAILURE = "timetables/DELETE_TIMETABLE_FAILURE";
