export const FETCH_ATTENDANCE_REQUEST = "attendance/FETCH_ATTENDANCE_REQUEST";
export const FETCH_ATTENDANCE_SUCCESS = "attendance/FETCH_ATTENDANCE_SUCCESS";
export const FETCH_ATTENDANCE_FAILURE = "attendance/FETCH_ATTENDANCE_FAILURE";
