export const FETCH_ATTENDANCE_REQUEST = "FETCH_ATTENDANCE_REQUEST";
export const FETCH_ATTENDANCE_SUCCESS = "FETCH_ATTENDANCE_SUCCESS";
export const FETCH_ATTENDANCE_FAILURE = "FETCH_ATTENDANCE_FAILURE";

export const SAVE_ATTENDANCE_REQUEST = "SAVE_ATTENDANCE_REQUEST";
export const SAVE_ATTENDANCE_SUCCESS = "SAVE_ATTENDANCE_SUCCESS";
export const SAVE_ATTENDANCE_FAILURE = "SAVE_ATTENDANCE_FAILURE";

export const FETCH_MY_ATTENDANCE_REQUEST = "FETCH_MY_ATTENDANCE_REQUEST";
export const FETCH_MY_ATTENDANCE_SUCCESS = "FETCH_MY_ATTENDANCE_SUCCESS";
export const FETCH_MY_ATTENDANCE_FAILURE = "FETCH_MY_ATTENDANCE_FAILURE";
