export const FETCH_CLASSES_REQUEST = "classes/FETCH_CLASSES_REQUEST";
export const FETCH_CLASSES_SUCCESS = "classes/FETCH_CLASSES_SUCCESS";
export const FETCH_CLASSES_FAILURE = "classes/FETCH_CLASSES_FAILURE";

export const CREATE_CLASS_REQUEST = "classes/CREATE_CLASS_REQUEST";
export const CREATE_CLASS_SUCCESS = "classes/CREATE_CLASS_SUCCESS";
export const CREATE_CLASS_FAILURE = "classes/CREATE_CLASS_FAILURE";

export const UPDATE_CLASS_REQUEST = "classes/UPDATE_CLASS_REQUEST";
export const UPDATE_CLASS_SUCCESS = "classes/UPDATE_CLASS_SUCCESS";
export const UPDATE_CLASS_FAILURE = "classes/UPDATE_CLASS_FAILURE";

export const DELETE_CLASS_REQUEST = "classes/DELETE_CLASS_REQUEST";
export const DELETE_CLASS_SUCCESS = "classes/DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_FAILURE = "classes/DELETE_CLASS_FAILURE";
