export const FETCH_SALARIES_REQUEST = "salaries/FETCH_SALARIES_REQUEST";
export const FETCH_SALARIES_SUCCESS = "salaries/FETCH_SALARIES_SUCCESS";
export const FETCH_SALARIES_FAILURE = "salaries/FETCH_SALARIES_FAILURE";

export const CREATE_SALARY_REQUEST = "salaries/CREATE_SALARY_REQUEST";
export const CREATE_SALARY_SUCCESS = "salaries/CREATE_SALARY_SUCCESS";
export const CREATE_SALARY_FAILURE = "salaries/CREATE_SALARY_FAILURE";

export const UPDATE_SALARY_REQUEST = "salaries/UPDATE_SALARY_REQUEST";
export const UPDATE_SALARY_SUCCESS = "salaries/UPDATE_SALARY_SUCCESS";
export const UPDATE_SALARY_FAILURE = "salaries/UPDATE_SALARY_FAILURE";

export const DELETE_SALARY_REQUEST = "salaries/DELETE_SALARY_REQUEST";
export const DELETE_SALARY_SUCCESS = "salaries/DELETE_SALARY_SUCCESS";
export const DELETE_SALARY_FAILURE = "salaries/DELETE_SALARY_FAILURE";
