export const FETCH_MARKS_REQUEST = "marks/FETCH_MARKS_REQUEST";
export const FETCH_MARKS_SUCCESS = "marks/FETCH_MARKS_SUCCESS";
export const FETCH_MARKS_FAILURE = "marks/FETCH_MARKS_FAILURE";

export const CREATE_MARKS_REQUEST = "marks/CREATE_MARKS_REQUEST";
export const CREATE_MARKS_SUCCESS = "marks/CREATE_MARKS_SUCCESS";
export const CREATE_MARKS_FAILURE = "marks/CREATE_MARKS_FAILURE";

export const UPDATE_MARKS_REQUEST = "marks/UPDATE_MARKS_REQUEST";
export const UPDATE_MARKS_SUCCESS = "marks/UPDATE_MARKS_SUCCESS";
export const UPDATE_MARKS_FAILURE = "marks/UPDATE_MARKS_FAILURE";

export const DELETE_MARKS_REQUEST = "marks/DELETE_MARKS_REQUEST";
export const DELETE_MARKS_SUCCESS = "marks/DELETE_MARKS_SUCCESS";
export const DELETE_MARKS_FAILURE = "marks/DELETE_MARKS_FAILURE";
