export const FETCH_HOMEWORK_REQUEST = "homework/FETCH_HOMEWORK_REQUEST";
export const FETCH_HOMEWORK_SUCCESS = "homework/FETCH_HOMEWORK_SUCCESS";
export const FETCH_HOMEWORK_FAILURE = "homework/FETCH_HOMEWORK_FAILURE";

export const CREATE_HOMEWORK_REQUEST = "homework/CREATE_HOMEWORK_REQUEST";
export const CREATE_HOMEWORK_SUCCESS = "homework/CREATE_HOMEWORK_SUCCESS";
export const CREATE_HOMEWORK_FAILURE = "homework/CREATE_HOMEWORK_FAILURE";

export const UPDATE_HOMEWORK_REQUEST = "homework/UPDATE_HOMEWORK_REQUEST";
export const UPDATE_HOMEWORK_SUCCESS = "homework/UPDATE_HOMEWORK_SUCCESS";
export const UPDATE_HOMEWORK_FAILURE = "homework/UPDATE_HOMEWORK_FAILURE";

export const DELETE_HOMEWORK_REQUEST = "homework/DELETE_HOMEWORK_REQUEST";
export const DELETE_HOMEWORK_SUCCESS = "homework/DELETE_HOMEWORK_SUCCESS";
export const DELETE_HOMEWORK_FAILURE = "homework/DELETE_HOMEWORK_FAILURE";
